---
title: "MovieLens: ejemplo de filtrado colaborativo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sistemas de recomendación: regularización espectral

```{r, message =FALSE}
library(softImpute)
```

## Estudio de la matriz 100k

```{r}
# lectura
dBrut=read.csv("ml-ratings100k.csv")
```

```{r}
# extracción de conjunto test y conjunto train
dTestInd=sample(nrow(dBrut),nrow(dBrut)/10,replace=FALSE)
dTest=dBrut[dTestInd,1:3]
dTrain=dBrut[-dTestInd,1:3]
```

```{r}
hist(recom)
```

```{r}
dTrainSparse=Incomplete(dTrain$userId,dTrain$movieId,dTrain$rating)
lambda = 1
res=softImpute(dTrainSparse,rank.max=4,type="als",lambda=lambda,maxit=200)
recom=impute(res,dTest[,1],dTest[,2]);recom[recom>5]=5;recom[recom<0]=0
error = sqrt(mean((dTest[,3]-recom)**2))
max_iteraciones = 100
extremo_inferior = 0
extremo_superior = 5
for (i in 1:max_iteraciones){
  cat("[ ",extremo_inferior," , ",extremo_superior,"]\n")
  cat("lambda ",lambda,"\n")
  lambda_nueva = runif(1,extremo_inferior,extremo_superior)
  cat("Nuevo lambda ",lambda_nueva,"\n")
  res=softImpute(dTrainSparse,rank.max=4,type="als",lambda=lambda_nueva,maxit=200)
  recom=impute(res,dTest[,1],dTest[,2]);recom[recom>5]=5;recom[recom<0]=0
  error_nuevo = sqrt(mean((dTest[,3]-recom)**2))
  if((abs(error_nuevo-error)<=0.0001) | (abs(lambda_nueva-lambda)<=0.01)){
    #Añadir validación cruzada y una tolerancia mayor.
    break;cat(i," iteraciones\n")
  }
  cat("Error ",error,"\n")
  cat("Error nuevo ",error_nuevo,"\n")
  if(error_nuevo<error){
    cat("MEJOOORA\n")
    lambda = lambda_nueva
    error = error_nuevo
    if(lambda_nueva >= lambda){
      extremo_inferior = lambda
      extremo_superior = extremo_superior
    }else{
      extremo_inferior = extremo_inferior
      extremo_superior = lambda
    }
  }else{
    cat("NOOO MEJOOORA\n")
    if(lambda_nueva >= lambda){
      extremo_inferior = extremo_inferior
      extremo_superior = lambda_nueva
    }else{
      extremo_inferior = lambda_nueva
      extremo_superior = extremo_superior
    }
  }
  cat("--------------------\n")
}
cat("Lambda bueno: ", lambda,"\n")
cat("Error: ", error,"\n")
```